-- SQL Script to set up Supabase tables for Fire Mail

-- 1. Recipients Table
CREATE TABLE IF NOT EXISTS recipients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    status TEXT DEFAULT 'pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 2. Templates Table
CREATE TABLE IF NOT EXISTS templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    subject TEXT,
    body TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 3. Sent History Table
CREATE TABLE IF NOT EXISTS sent_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_email TEXT,
    subject TEXT,
    body TEXT,
    status TEXT,
    error TEXT,
    sent_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 4. Schedules Table
CREATE TABLE IF NOT EXISTS schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE,
    time TIME,
    scheduled_at TIMESTAMP WITH TIME ZONE,
    subject TEXT,
    body TEXT,
    selected_recipients JSONB,
    status TEXT DEFAULT 'pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Optional: Add RLS (Row Level Security) if needed
-- For now, we assume the Vercel backend uses the Service Role or Anon key with appropriate permissions.
